### ISSUE TITLE
Ability to remove the header entirely for the blog

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/app-tiny-blog#1]
When adding the blog to a site that already has a header in place, we'll have double headers. Would be nice with a setting (option-set, with blog title nested?) on the app itself (site.xml) to disable the entire blog header block (the orange block and the text, not only the text).

![screenshot 2019-02-06 at 13 33 24](https://user-images.githubusercontent.com/1465598/52341793-d9e63a00-2a13-11e9-8e0f-4ec182bc0e88.png)

**Comment by poi33** [comment]
This is now in the 1.0.1 version.
If you can push it to the maven repo we can update it on market. @Bellfalasch
